layout_spectrum: 0.4531915
color:
  saturation: 0.09534768
  lightness: 0.403658
  brandStrength: 0.08037236
  rhythmicContrast: 0.2555366
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.9727505
name: Holt Adventures
