name: Holt Adventures
favicon: null
layout_spectrum: 0.21477
typography_spectrum: 0.87642
title: Holt Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b7576'
    - '#37414a'
    - '#010101'
    - '#f3f4ee'
    - '#c8c9c1'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
