name: Holt Adventures
favicon: null
layout_spectrum: 0.21477
typography_spectrum: 0.87642
title: Holt Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf6ff'
    - '#1b1821'
    - '#3d8811'
    - '#ae937e'
    - '#b54a50'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
