name: Holt Adventures
favicon: null
layout_spectrum: 0.26414
typography_spectrum: 0.87642
title: Holt Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#364049'
    - '#000000'
    - '#6d7778'
    - '#f4f5ef'
    - '#bebfba'
  brandStrength: 0.08037236
  lightness: 0.403658
  saturation: 0.09534768
  rhythmicContrast: 0.2555366
purpose: []
